version: "3"
networks:
  rar:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
      - subnet: 172.16.6.0/24
        ip_range: 172.16.6.51/32
        gateway: 172.16.6.254

volumes:
    config:

services:
  dns-server:
    container_name: dns-server
    hostname: dns-server
    image: technitium/dns-server:latest
    # For DHCP deployments, use "host" network mode and remove all the port mappings, including the ports array by commenting them
    # network_mode: "host"
    ports:
      - "5380:5380/tcp" #DNS web console (HTTP)
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
      - "80:80/tcp" #DNS-over-HTTP service (use with reverse proxy or certbot certificate renewal)
    environment:
      - DNS_SERVER_DOMAIN=ns.rar.test # Voir RFC 2606
    volumes:
      - config:/etc/dns
    networks:
      - rar
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000