services:
  nautobot:
    image: networktocode/nautobot
    depends_on:
      - "db"
      - "redis"
    env_file:
       - "local.env"
       - "creds.env"
    ports:
      - "8443:8843"
      - "8080:8080"
  redis:
    image: "redis:6-alpine"
    command:
      - "sh"
      - "-c"  # this is to evaluate the $NAUTOBOT_REDIS_PASSWORD from the env
      - "redis-server --appendonly yes --requirepass $$NAUTOBOT_REDIS_PASSWORD"
    env_file:
      - "local.env"
      - "creds.env"
  db:
    image: "postgres:13-alpine"
    env_file:
      - "local.env"
      - "creds.env"
    command:
      - "-c"
      - "max_connections=1000"
    volumes:
      # - "./nautobot.sql:/tmp/nautobot.sql"
      - "postgres_data:/var/lib/postgresql/data"
    healthcheck:
      test: "pg_isready --username=$$POSTGRES_USER --dbname=$$POSTGRES_DB"
      interval: "10s"
      timeout: "5s"
      retries: 10
    ports:
      - "5432:5432"

volumes:
  postgres_data: {}

